app:
  title: Backstage
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  cors:
    origin: http://localhost:7007
    methods: [GET, POST, PUT, DELETE]
    credentials: true

# This is for local development only
auth:
  environment: development
  providers: {}

catalog:
  locations:
    - type: file
      target: ../../catalog-info.yaml